#!/usr/bin/env ruby
# encoding: utf-8

require 'rubygems'
require 'erb'
require 'fileutils'
require 'micro-optparse'
require 'rexml/document'
gem 'google_drive', '>=1.0.0'
require 'google_drive'
require "google/api_client"
require "google/api_client/client_secrets"
require "google/api_client/auth/installed_app"
require_relative 'helpers/string'
require_relative 'helpers/read_term'

def copy_with_path(src, dst)
  FileUtils.mkdir_p(File.dirname(dst))
  FileUtils.cp(src, dst)
end

def show_error(error_string)
  puts 'Error!'.red
  puts error_string
  exit
end

def process_template(template_name, target_directory, generated_file_name)
  input_file = File.open("templates/"+template_name, "rb")
  template = input_file.read
  input_file.close
  renderer = ERB.new(template)
  output = renderer.result()
  output_file = File.new(generated_file_name, "w")
  output_file.write(output)
  output_file.close
  copy_with_path(generated_file_name, target_directory+generated_file_name)
  FileUtils.rm(generated_file_name)
end

# Reading from iOS

def read_from_ios(language, file, terms, keep_keys)
  puts "Parsing filename : #{file}"

  f = nil
  begin
    f = File.open(file, "r") 
  rescue Exception => e
    puts "File not found"
    return
  end

  current_comment = nil
  f.each_line do |line|
    if line.start_with?("//")
      # Disabled comments as there is no way of matching them
      # puts "Comment line #{line.gsub("//","")}"
      # term = ReadTerm.new("[COMMENT]")
      # term.add_value(language, line.gsub("//",""))
      # terms << term
    elsif line.start_with?("/*")
    elsif line.start_with?("\"")
      uglyKey = line.split("=", 2).first
      uglyValue = line.split("=", 2).last
      key = uglyKey[/\"(.*?)\"/m, 1]
      value = uglyValue[/\"(.*?)\"/m, 1]
      puts "Data line #{key},#{value}"
      add_term(terms, language, key, value, keep_keys)
    end
  end
end

# Generation for Android

def generate_android(language, target_directory)
  @current_lang = language
  process_template 'android_localizable.erb', target_directory, 'escape_strings.xml'
  puts ' > '+language.yellow
end

def read_from_android(language, file, terms, keep_keys)

  puts "Parsing filename : #{file}"

  f = nil
  begin
    f = File.open(file, "r") 
  rescue Exception => e
    puts "File not found"
    return
  end

  doc, posts = REXML::Document.new(f), []
  doc.elements.each('resources/*') do |p|
    puts "Element: #{p.attributes["name"] } value: #{p.text}"
    key = p.attributes["name"]
    value = p.text
    add_term(terms, language, key, value, keep_keys)
  end

end

# general

def add_term(terms, language, key, value, keep_keys = false)
  #searching for same key
  term = ReadTerm.new(key, keep_keys)
  found = false
  terms.each do |theTerm|
    if theTerm.keyword == term.keyword
      term = theTerm
      found = true
      break
    end
  end

  #if key not found create new one
  if !found
    terms << term
  end
  # adding value to term
  term.add_value(language, value)
end

# Parsing and commandline checks

show_error 'No parameters specified. Use the flag --help to see them all.' unless ARGV.size > 0

options = Parser.new do |p|
  p.banner = 'localizable-generator (c) 2013 EKGDev <elikohen@gmail.com>'
  p.version = '0.2'
  p.option :client, 'Client json path', :default => '', :short => 'u'
  p.option :spreadsheet, 'Spreadsheet containing the localization info', :default => 'example-spreadsheet'
  p.option :output_ios, 'Path to the iOS localization directory', :default => '/the_path/Localizables/', :short => 'i'
  p.option :output_android, 'Path to the resource directory of an Android project', :default => '/the_path/res/', :short => 'a'
  p.option :output_json, 'Path to the JSON localization directory', :default => '/the_path/strings/', :short => 'j'
  p.option :keep_keys, 'Whether to maintain original keys or not', :default => false, :short => 'k'
end.process!

client_json_path = options[:client]
ios_path = options[:output_ios]
android_path = options[:output_android]
json_path = options[:output_json]
spreadsheet = options[:spreadsheet]
keep_keys = options[:keep_keys]

has_ios = ios_path != '/the_path/Localizables/'
has_android = android_path != '/the_path/res/'
has_json = json_path != '/the_path/strings/'

show_error 'You must provide a Client json path' if client_json_path.blank?
show_error 'You must provide a iOS, Android or JSON path at least to proceed' unless has_android || has_ios || has_json

# Get the spreadsheet from Google Drive
puts 'Logging in to Google Drive...'

CREDENTIALS_PATH = Dir.home + '/.locgen/users.json'

def authorize(certificate)
  FileUtils.mkdir_p(File.dirname(CREDENTIALS_PATH))
  file_store = Google::APIClient::FileStore.new(CREDENTIALS_PATH)
  storage = Google::APIClient::Storage.new(file_store)

  auth = storage.authorize

  if auth.nil? || (auth.expired? && auth.refresh_token.nil?)
    client_secrets = Google::APIClient::ClientSecrets.load(certificate)
    flow = Google::APIClient::InstalledAppFlow.new(
      :client_id => client_secrets.client_id,
      :client_secret => client_secrets.client_secret,
      :scope => ['https://www.googleapis.com/auth/drive','https://spreadsheets.google.com/feeds/']
    )
    auth = flow.authorize(storage)
    puts "Credentials saved to #{CREDENTIALS_PATH}" unless auth.nil?
  end
  auth
end

client = Google::APIClient.new(
    :application_name => "Ztory Localizables",
    :application_version => "1.0"
  )
client.authorization = authorize(client_json_path)

access_token = client.authorization.access_token

puts 'Logging in to Google Drive...'
begin
  session = GoogleDrive.login_with_oauth(access_token)
rescue
  show_error 'Couldn\'t access Google Drive. Check your json access token!'
end

# Recover our spreadsheets

puts 'Logged.'.cyan
puts "Searching for #{spreadsheet}..."
matching_spreadsheets = []

session.spreadsheets.each do |s|
  matching_spreadsheets << s if s.title.downcase.include?(spreadsheet.downcase) && s.title.include?('[Localizables]')
end

if matching_spreadsheets.count > 1
  puts 'Found:'.cyan
  matching_spreadsheets.each { |ms| puts ms.title.red }
  show_error 'More than one match found. You have to be more specific!'
elsif matching_spreadsheets.count == 0
  show_error "Unable to find any spreadsheet matching your criteria: #{spreadsheet}"
end

found_spreadsheet = matching_spreadsheets[0]
puts "Found one match: #{found_spreadsheet.title}".cyan

puts "Processing #{found_spreadsheet.title}..."
worksheet = found_spreadsheet.worksheets[0]
show_error 'Unable to retrieve the first worksheet from the spreadsheet' if worksheet.nil?


#Reading metadata from spreadsheet

first_valid_row_index = nil

for row in 1..worksheet.max_rows
  first_valid_row_index = row if worksheet[row, 1].downcase == '[key]'
end

languages = Hash.new('languages')
default_language = nil

for column in 2..worksheet.max_cols
  col_text = worksheet[first_valid_row_index, column]
  default_language = col_text.downcase.gsub('*','') if col_text.include? '*'
  languages.store col_text.downcase.gsub('*',''), column unless col_text.blank?
end

puts 'Languages: ' + languages.keys.join(', ').yellow

#Reading data
@terms = []

  #Default langue to create keys and comments
if default_language
  if has_ios
    the_path = ios_path + "#{default_language}.lproj/Localizable.strings"
    read_from_ios(default_language, the_path, @terms, keep_keys)
  elsif has_android
    the_path = android_path + "res/values/strings.xml"
    read_from_android(default_language, the_path, @terms, keep_keys)
  end
end

  #Rest of the languages just to fill data
languages.keys.each do |lang|
  unless lang == default_language
    if has_ios
      the_path = ios_path + "#{lang}.lproj/Localizable.strings"
      read_from_ios(lang, the_path, @terms, keep_keys)
    elsif has_android
      the_path = android_path + "res/values-#{lang}/strings.xml"
      read_from_android(lang, the_path, @terms, keep_keys)
    end
  end
end 


# Writing the spreadsheet

current_term_row = first_valid_row_index+1

@terms.each do |term|
  puts "Writing term #{term.keyword}"
  key = term.keyword
  worksheet[current_term_row, 1] = key
  languages.each do |lang, column_index|
    worksheet[current_term_row, column_index] = term.values[lang]
  end
  current_term_row = current_term_row + 1
end

worksheet[current_term_row, 1] = '[end]'
worksheet.save

puts 'Written.'.cyan

puts 'Done! - everything went smoothly :)'.green